# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Archer Invasion' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Archer Invasion

  pod ‘Firebase/Core’
  pod ‘Firebase’
  pod 'Google-Mobile-Ads-SDK'


  target 'Archer InvasionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Archer InvasionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
